export const MOOD_LEVELS = [
  {
    category: "Positive",
    subcategory: "Basic Emotion",
    animation: "/animations/happy.json",
    mood: "Happy",
    color: "#FFB300",
    bgColor: "#FFF8E1",
    emoji: "",
    score: 5,
  },
  {
    category: "Negative",
    subcategory: "Basic Emotion",
    animation: "/animations/sad.json",
    mood: "Sad",
    color: "#5C6BC0",
    bgColor: "#E8EAF6",
    emoji: "",
    score: 2,
  },
  {
    category: "Negative",
    subcategory: "Basic Emotion",
    animation: "/animations/angry.json",
    mood: "Angry",
    color: "#D32F2F",
    bgColor: "#FFEBEE",
    emoji: "",
    score: 1,
  },
  {
    category: "Negative",
    subcategory: "Basic Emotion",
    animation: "/animations/anxious.json",
    mood: "Fearful",
    color: "#F59E0B",
    bgColor: "#FFF7ED",
    emoji: "",
    score: 2,
  },
  {
    category: "Negative",
    subcategory: "Basic Emotion",
    animation: "/animations/tired.json",
    mood: "Disgust",
    color: "#8B5CF6",
    bgColor: "#F5F3FF",
    emoji: "",
    score: 1,
  },
];
