export const MOOD_LEVELS = [
  // POSITIVE - LOW ENERGY
  {
    category: "Positive",
    subcategory: "Low Energy",
    animation: "/animations/relax.json",
    mood: "Calm",
    color: "#4CAF50",
    bgColor: "#E8F5E9",
    emoji: "😌",
    score: 4,
  },
  {
    category: "Positive",
    subcategory: "Low Energy",
    animation: "/animations/relax.json",
    mood: "Relaxed",
    color: "#66BB6A",
    bgColor: "#E8F5E9",
    emoji: "😌",
    score: 4,
  },
  {
    category: "Positive",
    subcategory: "Low Energy",
    animation: "/animations/content.json",
    mood: "Content",
    color: "#26A69A",
    bgColor: "#E0F2F1",
    emoji: "😊",
    score: 4.2,
  },
  {
    category: "Positive",
    subcategory: "Low Energy",
    animation: "/animations/relax.json",
    mood: "Peaceful",
    color: "#00ACC1",
    bgColor: "#E0F7FA",
    emoji: "😇",
    score: 4.5,
  },
  {
    category: "Positive",
    subcategory: "Low Energy",
    animation: "/animations/happy.json",
    mood: "Grateful",
    color: "#673AB7",
    bgColor: "#EDE7F6",
    emoji: "🙏",
    score: 5,
  },

  // POSITIVE - HIGH ENERGY
  {
    category: "Positive",
    subcategory: "High Energy",
    animation: "/animations/happy.json",
    mood: "Excited",
    color: "#FFD700",
    bgColor: "#FFF9C4",
    emoji: "🤩",
    score: 5,
  },
  {
    category: "Positive",
    subcategory: "High Energy",
    animation: "/animations/happy.json",
    mood: "Joyful",
    color: "#FFB300",
    bgColor: "#FFF8E1",
    emoji: "😄",
    score: 5,
  },
  {
    category: "Positive",
    subcategory: "High Energy",
    animation: "/animations/happy.json",
    mood: "Thrilled",
    color: "#FF8F00",
    bgColor: "#FFF3E0",
    emoji: "🥳",
    score: 5,
  },
  {
    category: "Positive",
    subcategory: "High Energy",
    animation: "/animations/happy.json",
    mood: "Inspired",
    color: "#9C27B0",
    bgColor: "#F3E5F5",
    emoji: "✨",
    score: 4.7,
  },
  {
    category: "Positive",
    subcategory: "High Energy",
    animation: "/animations/happy.json",
    mood: "Playful",
    color: "#E91E63",
    bgColor: "#FCE4EC",
    emoji: "😜",
    score: 4.5,
  },

  // NEGATIVE - LOW ENERGY
  {
    category: "Negative",
    subcategory: "Low Energy",
    animation: "/animations/sad.json",
    mood: "Depressed",
    color: "#5C6BC0",
    bgColor: "#E8EAF6",
    emoji: "😔",
    score: 1.0,
  },
  {
    category: "Negative",
    subcategory: "Low Energy",
    animation: "/animations/tired.json",
    mood: "Tired",
    color: "#8D6E63",
    bgColor: "#EFEBE9",
    emoji: "😴",
    score: 2.0,
  },
  {
    category: "Negative",
    subcategory: "Low Energy",
    animation: "/animations/sad.json",
    mood: "Disappointed",
    color: "#7E57C2",
    bgColor: "#F3E5F5",
    emoji: "😞",
    score: 1.5,
  },
  {
    category: "Negative",
    subcategory: "Low Energy",
    animation: "/animations/angry.json",
    mood: "Annoyed",
    color: "#FB8C00",
    bgColor: "#FFF3E0",
    emoji: "😒",
    score: 2.5,
  },
  {
    category: "Negative",
    subcategory: "Low Energy",
    animation: "/animations/sad.json",
    mood: "Bored",
    color: "#B0BEC5",
    bgColor: "#F5F5F5",
    emoji: "😑",
    score: 2.2,
  },

  // NEGATIVE - HIGH ENERGY
  {
    category: "Negative",
    subcategory: "High Energy",
    animation: "/animations/anxious.json",
    mood: "Anxious",
    color: "#FFA726",
    bgColor: "#FFF3E0",
    emoji: "😰",
    score: 1.5,
  },
  {
    category: "Negative",
    subcategory: "High Energy",
    animation: "/animations/anxious.json",
    mood: "Overwhelmed",
    color: "#F44336",
    bgColor: "#FFEBEE",
    emoji: "🤯",
    score: 1.0,
  },
  {
    category: "Negative",
    subcategory: "High Energy",
    animation: "/animations/anxious.json",
    mood: "Panicked",
    color: "#D32F2F",
    bgColor: "#FFEBEE",
    emoji: "😱",
    score: 0.5,
  },
  {
    category: "Negative",
    subcategory: "High Energy",
    animation: "/animations/angry.json",
    mood: "Irritated",
    color: "#E64A19",
    bgColor: "#FBE9E7",
    emoji: "😤",
    score: 2.0,
  },
  {
    category: "Negative",
    subcategory: "High Energy",
    animation: "/animations/angry.json",
    mood: "Angry",
    color: "#D32F2F",
    bgColor: "#FFEBEE",
    emoji: "😠",
    score: 0.5,
  },
];
